FROM nodered/node-red

# Copy package.json to the WORKDIR so npm builds all
# of your added nodes modules for Node-RED

WORKDIR /usr/src/node-red
COPY ["package.json", "package-lock.json*", "./"]
RUN npm install --unsafe-perm --no-update-notifier --no-fund --include=dev
RUN mkdir -p /usr/src/node-red/.node-red
RUN mkdir -p /usr/src/node-red/.node-red
RUN chown -R 1000:1000 /usr/src/node-red
RUN timeout 5 npm start # workaround to initalize working directory
RUN cd /usr/src/node-red/.node-red && npm install /usr/src/node-red
RUN chown -R 1000:1000 /usr/src/node-red
COPY . .
USER root
RUN chown -R 1000:1000 /usr/src/node-red

USER 1000:1000

RUN npm install
# port: 1880
EXPOSE 1880
# Copy _your_ Node-RED project files into place
# NOTE: This will only work if you DO NOT later mount /data as an external volume.
#       If you need to use an external volume for persistence then
#       copy your settings and flows files to that volume instead.

# COPY settings.js /data/settings.js
# COPY flows_cred.json /data/flows_cred.json
# COPY flows.json /data/flows.json

# You should add extra nodes via your package.json file but you can also add them here:
#WORKDIR /usr/src/node-red
#RUN npm install node-red-node-smooth
